"""empty message

Revision ID: 17863f2243ca
Revises: 
Create Date: 2021-08-04 23:26:00.811205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17863f2243ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('listbuku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul_buku', sa.Text(), nullable=True),
    sa.Column('penulis', sa.Text(), nullable=True),
    sa.Column('penerbit', sa.Text(), nullable=True),
    sa.Column('tahun', sa.Integer(), nullable=True),
    sa.Column('id_pemilik', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pemilik'], ['user_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listbuku')
    op.drop_table('user_tbl')
    # ### end Alembic commands ###
