"""empty message

Revision ID: e0cec502caa3
Revises: 17863f2243ca
Create Date: 2021-08-04 23:33:07.254171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0cec502caa3'
down_revision = '17863f2243ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listbuku', sa.Column('id_peminjam', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listbuku', 'id_peminjam')
    # ### end Alembic commands ###
